export const TAGLINES = [
  "Your keyboard didn't deserve that anyway.",
  "Pressing charges? No. Just pressing this.",
  "Violence: 0. Satisfaction: rising.",
  "Unhinged? Maybe. Calm? Getting there.",
  "This meeting could've been a press.",
  "No thoughts. Just pressing.",
  "The button has seen worse. Keep going.",
  "Stress level: slightly less catastrophic.",
  "HR would prefer this.",
  "Let it out.",
  "Your therapist doesn't need to know about this one.",
  "Deep breaths are overrated. Press this instead.",
  "Not a punching bag. Close enough.",
  "Press. Breathe. Repeat.",
  "Press something.",
  "Press away.",
  "A button cheaper than therapy.",
] as const;
